### ISSUE TITLE
(한우엽2 Node JS) 겜프프로젝트 과정평가용(방문기록)

### ISSUE THREAD

**Issue by GGMinwok** [notdevblue/OneTwoShotgun#1]
5/26 깃허브 접속확인

**Comment by GGMinwok** [comment]
오늘 기록할 때 지금까지 한 것(오늘 이전꺼~), 6/8 오늘 1-3교시에 한 것 구분해서 과정 기록 해주기!

**Comment by notdevblue** [comment]
## 6/16 일지

### 서버
* 접속 처리
* 로그인 처리 중
* 회원가입 처리 중

* * *

### 클라이언트
* 접속 처리 중
* 로그인 처리 중
* 회원가입 처리 중

**Comment by GGMinwok** [comment]
6/22 기록확인함

**Comment by notdevblue** [comment]
## 6/23 까지 일지

### 서버
* 이동
* 입장
* 퇴장
* 발사
* 총알 연산 처리 중 (서버사이드)
* 피격 처리 중 (서버사이드?)
* 사망 처리 중 (서버사이드?)

* * *

### 클라이언트
* 서버에서 보내는 데이터 처리
* UI 관련 개발 중

**Comment by notdevblue** [comment]
## 6/26 일까지 일지

### 서버
* 끝

* * *

### 클라이언트
* 끝

**Comment by GGMinwok** [comment]
어잉... 왜 클로즈 해둔거야... 사라진 줄 알았자나... 
6/30 확인하고 갑니다. 마지막 과정 확인!!! 감점할 뻔 했네....
